package com.smartparking.notification;

public enum NotificationType {
    BOOKING_CONFIRMED,
    BOOKING_REQUESTED,
    BOOKING_APPROVED,
    BOOKING_DECLINED,
    BOOKING_EXPIRED_REQUEST,
    BOOKING_CANCELLED,
    BOOKING_REFUNDED,
    BOOKING_STARTING_SOON,
    BOOKING_COMPLETED,
    OWNER_NEW_BOOKING,
    OWNER_APPROVAL_NEEDED,
    OWNER_APPROVAL_REMINDER,
    OWNER_BOOKING_CANCELLED,
    OWNER_VERIFIED,
    OWNER_REJECTED,
    LISTING_APPROVED,
    LISTING_REJECTED,
    OWNER_NEW_REVIEW
}
