CREATE TABLE reviews (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id       BIGINT        NOT NULL UNIQUE REFERENCES bookings (id),
    listing_id       BIGINT        NOT NULL REFERENCES parking_listings (id),
    driver_id        BIGINT        NOT NULL REFERENCES users (id),
    rating           SMALLINT      NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment          VARCHAR(1000),
    owner_reply      VARCHAR(500),
    owner_replied_at TIMESTAMPTZ,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_reviews_listing ON reviews (listing_id, created_at DESC);
