-- Phase 7: admin panel. Platform settings, admin audit log, disputes, review moderation and city tiers/activation.

-- Key/value settings. No foreign key on updated_by on purpose: settings are reference data that must outlive users.
CREATE TABLE platform_settings (
    key        VARCHAR(60)  PRIMARY KEY,
    value      VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by BIGINT
);

INSERT INTO platform_settings (key, value) VALUES
    ('platform_fee_percent', '10'),
    ('gst_percent', '18'),
    ('hold_minutes', '10'),
    ('approval_hours', '2'),
    ('request_min_lead_minutes', '30'),
    ('price_tier1_min', '20'),
    ('price_tier1_max', '150'),
    ('price_tier2_min', '10'),
    ('price_tier2_max', '100'),
    ('price_tier3_min', '5'),
    ('price_tier3_max', '80');

CREATE TABLE admin_actions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    BIGINT        NOT NULL REFERENCES users (id),
    action      VARCHAR(60)   NOT NULL,
    target_type VARCHAR(40)   NOT NULL,
    target_id   BIGINT,
    details     VARCHAR(1000),
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_admin_actions_created ON admin_actions (created_at DESC, id DESC);

CREATE TABLE disputes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id         BIGINT         NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
    raised_by          BIGINT         NOT NULL REFERENCES users (id),
    category           VARCHAR(20)    NOT NULL
        CHECK (category IN ('NO_ACCESS','SLOT_OCCUPIED','OVERSTAY','DAMAGE','PAYMENT','OTHER')),
    description        VARCHAR(2000)  NOT NULL,
    status             VARCHAR(20)    NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','UNDER_REVIEW','RESOLVED')),
    owner_response     VARCHAR(1000),
    owner_responded_at TIMESTAMPTZ,
    admin_notes        VARCHAR(1000),
    resolution         VARCHAR(20)    CHECK (resolution IN ('REFUND_FULL','REFUND_PARTIAL','NO_REFUND','WARNING')),
    resolution_amount  NUMERIC(10, 2) CHECK (resolution_amount >= 0),
    resolved_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ    NOT NULL DEFAULT now()
);
CREATE INDEX idx_disputes_booking ON disputes (booking_id);
CREATE INDEX idx_disputes_status_created ON disputes (status, created_at);
-- One unresolved dispute per booking, enforced by the database so concurrent requests cannot both open one.
CREATE UNIQUE INDEX uq_disputes_one_open_per_booking ON disputes (booking_id) WHERE status <> 'RESOLVED';

ALTER TABLE reviews
    ADD COLUMN hidden_at     TIMESTAMPTZ,
    ADD COLUMN hidden_reason VARCHAR(300);

-- The GST rate a booking was priced with, so receipts keep showing it after the rate is edited. Existing rows
-- were all priced at 18%.
ALTER TABLE bookings ADD COLUMN gst_percent NUMERIC(5, 2) NOT NULL DEFAULT 18;

-- 1 = metro, 2 = other state capitals, 3 = everything else.
ALTER TABLE cities
    ADD COLUMN tier   SMALLINT NOT NULL DEFAULT 3 CHECK (tier BETWEEN 1 AND 3),
    ADD COLUMN active BOOLEAN  NOT NULL DEFAULT TRUE;

UPDATE cities SET tier = 1
WHERE slug IN ('mumbai', 'new-delhi', 'bengaluru', 'chennai', 'kolkata', 'hyderabad', 'pune', 'ahmedabad');
UPDATE cities SET tier = 2 WHERE is_capital AND tier = 3;

-- Admin cancellations: booking actors/cancelled_by already allow 'ADMIN' (V6) and notifications.type is unconstrained.
