ALTER TABLE owner_profiles DROP COLUMN document_url;
ALTER TABLE owner_profiles
    ADD COLUMN document_key          VARCHAR(500),
    ADD COLUMN document_content_type VARCHAR(100),
    ADD COLUMN document_submitted_at TIMESTAMPTZ;
ALTER TABLE owner_profiles
    ADD CONSTRAINT chk_owner_document_type CHECK (document_type IS NULL OR document_type IN
        ('AADHAAR','PAN','DRIVING_LICENCE','PASSPORT','VOTER_ID','PROPERTY_DOCUMENT','UTILITY_BILL'));

CREATE TABLE parking_listings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id            BIGINT           NOT NULL REFERENCES users (id),
    city_id             BIGINT           NOT NULL REFERENCES cities (id),
    title               VARCHAR(120)     NOT NULL,
    description         VARCHAR(2000),
    address             VARCHAR(300)     NOT NULL,
    pincode             VARCHAR(6)       NOT NULL CHECK (pincode ~ '^[1-9][0-9]{5}$'),
    lat                 DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN 6 AND 38),
    lng                 DOUBLE PRECISION NOT NULL CHECK (lng BETWEEN 68 AND 98),
    listing_type        VARCHAR(20)      NOT NULL CHECK (listing_type IN ('METRO','OFFICE','COMMERCIAL','RESIDENTIAL','EVENT')),
    open_24x7           BOOLEAN          NOT NULL DEFAULT FALSE,
    rules               VARCHAR(2000),
    auto_approve        BOOLEAN          NOT NULL DEFAULT TRUE,
    status              VARCHAR(20)      NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT','PENDING_REVIEW','APPROVED','REJECTED','PAUSED','SUSPENDED')),
    rejection_reason    VARCHAR(500),
    price_per_hour      NUMERIC(10, 2)   CHECK (price_per_hour > 0),
    price_per_day       NUMERIC(10, 2)   CHECK (price_per_day > 0),
    price_per_month     NUMERIC(10, 2)   CHECK (price_per_month > 0),
    cancellation_policy VARCHAR(20)      NOT NULL DEFAULT 'MODERATE' CHECK (cancellation_policy IN ('FLEXIBLE','MODERATE','STRICT')),
    avg_rating          NUMERIC(2, 1)    NOT NULL DEFAULT 0,
    review_count        INT              NOT NULL DEFAULT 0,
    submitted_at        TIMESTAMPTZ,
    approved_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ      NOT NULL DEFAULT now()
);
CREATE INDEX idx_listings_owner ON parking_listings (owner_id);
CREATE INDEX idx_listings_status ON parking_listings (status);
CREATE INDEX idx_listings_city ON parking_listings (city_id);
CREATE INDEX idx_listings_lat_lng ON parking_listings (lat, lng);

CREATE TABLE listing_amenities (
    listing_id BIGINT      NOT NULL REFERENCES parking_listings (id) ON DELETE CASCADE,
    amenity    VARCHAR(30) NOT NULL CHECK (amenity IN ('COVERED','CCTV','EV_CHARGING','SECURITY_GUARD','WHEELCHAIR_ACCESS','WELL_LIT')),
    PRIMARY KEY (listing_id, amenity)
);

CREATE TABLE listing_photos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  BIGINT       NOT NULL REFERENCES parking_listings (id) ON DELETE CASCADE,
    url         VARCHAR(500) NOT NULL,
    storage_key VARCHAR(500),
    sort_order  INT          NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_listing_photos_listing ON listing_photos (listing_id);

CREATE TABLE parking_slots (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id   BIGINT      NOT NULL REFERENCES parking_listings (id) ON DELETE CASCADE,
    label        VARCHAR(20) NOT NULL,
    vehicle_type VARCHAR(20) NOT NULL CHECK (vehicle_type IN ('TWO_WHEELER','FOUR_WHEELER')),
    size         VARCHAR(10) NOT NULL CHECK (size IN ('SMALL','MEDIUM','LARGE')),
    active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_parking_slots_label ON parking_slots (listing_id, lower(label));

CREATE TABLE availability_rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  BIGINT      NOT NULL REFERENCES parking_listings (id) ON DELETE CASCADE,
    day_of_week INT         NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    open_time   TIME        NOT NULL,
    close_time  TIME        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (close_time > open_time),
    UNIQUE (listing_id, day_of_week)
);

CREATE TABLE availability_blocks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT       NOT NULL REFERENCES parking_listings (id) ON DELETE CASCADE,
    slot_id    BIGINT       REFERENCES parking_slots (id) ON DELETE CASCADE,
    start_time TIMESTAMPTZ  NOT NULL,
    end_time   TIMESTAMPTZ  NOT NULL,
    reason     VARCHAR(200),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CHECK (end_time > start_time)
);
CREATE INDEX idx_blocks_listing_time ON availability_blocks (listing_id, start_time);
