CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE vehicles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type         VARCHAR(20) NOT NULL CHECK (type IN ('TWO_WHEELER','FOUR_WHEELER')),
    plate_number VARCHAR(15) NOT NULL,
    make_model   VARCHAR(60),
    is_default   BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, plate_number)
);

CREATE TABLE bookings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_code      VARCHAR(12)    NOT NULL UNIQUE,
    driver_id         BIGINT         NOT NULL REFERENCES users (id),
    listing_id        BIGINT         NOT NULL REFERENCES parking_listings (id),
    slot_id           BIGINT         NOT NULL REFERENCES parking_slots (id),
    vehicle_id        BIGINT         REFERENCES vehicles (id) ON DELETE SET NULL,
    vehicle_type      VARCHAR(20)    NOT NULL CHECK (vehicle_type IN ('TWO_WHEELER','FOUR_WHEELER')),
    plate_number      VARCHAR(15)    NOT NULL,
    start_time        TIMESTAMPTZ    NOT NULL,
    end_time          TIMESTAMPTZ    NOT NULL,
    pricing_mode      VARCHAR(10)    NOT NULL,
    pricing_breakdown VARCHAR(100)   NOT NULL,
    base_amount       NUMERIC(10, 2) NOT NULL,
    platform_fee      NUMERIC(10, 2) NOT NULL,
    gst_amount        NUMERIC(10, 2) NOT NULL,
    total_amount      NUMERIC(10, 2) NOT NULL,
    refund_amount     NUMERIC(10, 2) NOT NULL DEFAULT 0,
    status            VARCHAR(20)    NOT NULL CHECK (status IN ('PENDING_PAYMENT','AWAITING_APPROVAL','CONFIRMED','ACTIVE','COMPLETED','CANCELLED','REJECTED','EXPIRED')),
    hold_expires_at   TIMESTAMPTZ,
    approval_deadline TIMESTAMPTZ,
    confirmed_at      TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ,
    cancelled_by      VARCHAR(10)    CHECK (cancelled_by IN ('DRIVER','OWNER','SYSTEM','ADMIN')),
    cancel_reason     VARCHAR(500),
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CHECK (end_time > start_time),
    CONSTRAINT bookings_no_overlap EXCLUDE USING gist (
        slot_id WITH =, tstzrange(start_time, end_time, '[)') WITH &&
    ) WHERE (status IN ('PENDING_PAYMENT','AWAITING_APPROVAL','CONFIRMED','ACTIVE'))
);
CREATE INDEX idx_bookings_driver ON bookings (driver_id, start_time DESC);
CREATE INDEX idx_bookings_listing ON bookings (listing_id, start_time);
CREATE INDEX idx_bookings_hold ON bookings (hold_expires_at) WHERE status = 'PENDING_PAYMENT';
CREATE INDEX idx_bookings_approval ON bookings (approval_deadline) WHERE status = 'AWAITING_APPROVAL';

CREATE TABLE booking_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  BIGINT      NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
    from_status VARCHAR(20),
    to_status   VARCHAR(20) NOT NULL,
    actor       VARCHAR(10) NOT NULL CHECK (actor IN ('DRIVER','OWNER','SYSTEM','ADMIN')),
    note        VARCHAR(500),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_booking_events_booking ON booking_events (booking_id, created_at);

CREATE TABLE payments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id          BIGINT         NOT NULL UNIQUE REFERENCES bookings (id) ON DELETE CASCADE,
    provider            VARCHAR(10)    NOT NULL CHECK (provider IN ('RAZORPAY','MOCK')),
    provider_order_id   VARCHAR(60)    NOT NULL UNIQUE,
    provider_payment_id VARCHAR(60)    UNIQUE,
    amount              NUMERIC(10, 2) NOT NULL,
    currency            VARCHAR(3)     NOT NULL DEFAULT 'INR',
    method              VARCHAR(30),
    status              VARCHAR(20)    NOT NULL CHECK (status IN ('CREATED','CAPTURED','FAILED','REFUNDED','PARTIALLY_REFUNDED')),
    failure_reason      VARCHAR(300),
    captured_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE TABLE refunds (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id         BIGINT         NOT NULL REFERENCES payments (id) ON DELETE CASCADE,
    provider_refund_id VARCHAR(60)    UNIQUE,
    amount             NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
    status             VARCHAR(20)    NOT NULL CHECK (status IN ('PENDING','PROCESSED','FAILED')),
    reason             VARCHAR(300),
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE TABLE owner_earnings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id       BIGINT         NOT NULL UNIQUE REFERENCES bookings (id) ON DELETE CASCADE,
    owner_id         BIGINT         NOT NULL REFERENCES users (id),
    gross            NUMERIC(10, 2) NOT NULL,
    commission       NUMERIC(10, 2) NOT NULL,
    net              NUMERIC(10, 2) NOT NULL,
    status           VARCHAR(20)    NOT NULL CHECK (status IN ('HELD','PENDING_PAYOUT','PAID','REVERSED')),
    payout_reference VARCHAR(60),
    paid_at          TIMESTAMPTZ,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT now()
);
CREATE INDEX idx_owner_earnings_owner ON owner_earnings (owner_id, status);

CREATE SEQUENCE invoice_number_seq START 1;
CREATE TABLE invoices (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(20) NOT NULL UNIQUE,
    booking_id     BIGINT      NOT NULL UNIQUE REFERENCES bookings (id) ON DELETE CASCADE,
    payment_id     BIGINT      NOT NULL REFERENCES payments (id),
    issued_at      TIMESTAMPTZ NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE webhook_events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_event_id VARCHAR(100) NOT NULL UNIQUE,
    event_type        VARCHAR(60)  NOT NULL,
    payload           TEXT         NOT NULL,
    processed_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
