import { lazyPage } from '../lib/lazyPage'

// Every page is its own chunk, loaded when its route is first visited; the layout around it (navbar, footer) is
// eager and shows a spinner where the page will be (see AppLayout). Role areas and heavy pages (map, charts) thereby
// stay out of the main bundle for everyone who never opens them. Each has a `preload()` to warm its chunk early.
export const AccountPage = lazyPage(() => import('./AccountPage'), 'AccountPage')
export const ListingPage = lazyPage(() => import('./ListingPage'), 'ListingPage')
export const CityPage = lazyPage(() => import('./CityPage'), 'CityPage')
export const HomePage = lazyPage(() => import('./HomePage'), 'HomePage')
export const NotificationsPage = lazyPage(() => import('./NotificationsPage'), 'NotificationsPage')
export const NotFoundPage = lazyPage(() => import('./NotFoundPage'), 'NotFoundPage')
export const SearchPage = lazyPage(() => import('./SearchPage'), 'SearchPage')
export const StatePage = lazyPage(() => import('./StatePage'), 'StatePage')
export const ForgotPasswordPage = lazyPage(() => import('./auth/ForgotPasswordPage'), 'ForgotPasswordPage')
export const LoginPage = lazyPage(() => import('./auth/LoginPage'), 'LoginPage')
export const RegisterPage = lazyPage(() => import('./auth/RegisterPage'), 'RegisterPage')
export const ResetPasswordPage = lazyPage(() => import('./auth/ResetPasswordPage'), 'ResetPasswordPage')
export const VerifyEmailPage = lazyPage(() => import('./auth/VerifyEmailPage'), 'VerifyEmailPage')
export const BookingDetailPage = lazyPage(() => import('./driver/BookingDetailPage'), 'BookingDetailPage')
export const CheckoutPage = lazyPage(() => import('./driver/CheckoutPage'), 'CheckoutPage')
export const MyBookingsPage = lazyPage(() => import('./driver/MyBookingsPage'), 'MyBookingsPage')
export const PaymentsPage = lazyPage(() => import('./driver/PaymentsPage'), 'PaymentsPage')
export const DisputeDetailPage = lazyPage(() => import('./driver/DisputeDetailPage'), 'DisputeDetailPage')
export const DisputesPage = lazyPage(() => import('./driver/DisputesPage'), 'DisputesPage')
export const DriverHomePage = lazyPage(() => import('./driver/DriverHomePage'), 'DriverHomePage')
export const DriverLayout = lazyPage(() => import('./driver/DriverLayout'), 'DriverLayout')
export const VehiclesPage = lazyPage(() => import('./driver/VehiclesPage'), 'VehiclesPage')
export const AdminBookingDetailPage = lazyPage(() => import('./admin/AdminBookingDetailPage'), 'AdminBookingDetailPage')
export const AdminBookingsPage = lazyPage(() => import('./admin/AdminBookingsPage'), 'AdminBookingsPage')
export const AdminLocationsPage = lazyPage(() => import('./admin/AdminLocationsPage'), 'AdminLocationsPage')
export const AdminPaymentsPage = lazyPage(() => import('./admin/AdminPaymentsPage'), 'AdminPaymentsPage')
export const AdminPayoutsPage = lazyPage(() => import('./admin/AdminPayoutsPage'), 'AdminPayoutsPage')
export const AdminReviewsPage = lazyPage(() => import('./admin/AdminReviewsPage'), 'AdminReviewsPage')
export const AdminUsersPage = lazyPage(() => import('./admin/AdminUsersPage'), 'AdminUsersPage')
export const AdminDisputeDetailPage = lazyPage(() => import('./admin/AdminDisputeDetailPage'), 'AdminDisputeDetailPage')
export const AdminDisputesPage = lazyPage(() => import('./admin/AdminDisputesPage'), 'AdminDisputesPage')
export const AdminHomePage = lazyPage(() => import('./admin/AdminHomePage'), 'AdminHomePage')
export const AdminAuditPage = lazyPage(() => import('./admin/AdminAuditPage'), 'AdminAuditPage')
export const AdminLayout = lazyPage(() => import('./admin/AdminLayout'), 'AdminLayout')
export const AdminListingReviewPage = lazyPage(() => import('./admin/AdminListingReviewPage'), 'AdminListingReviewPage')
export const AdminReportsPage = lazyPage(() => import('./admin/AdminReportsPage'), 'AdminReportsPage')
export const AdminSettingsPage = lazyPage(() => import('./admin/AdminSettingsPage'), 'AdminSettingsPage')
export const ListingQueuePage = lazyPage(() => import('./admin/ListingQueuePage'), 'ListingQueuePage')
export const OwnerQueuePage = lazyPage(() => import('./admin/OwnerQueuePage'), 'OwnerQueuePage')
export const ListingBlocksPage = lazyPage(() => import('./owner/ListingBlocksPage'), 'ListingBlocksPage')
export const ListingWizardPage = lazyPage(() => import('./owner/ListingWizardPage'), 'ListingWizardPage')
export const MyListingsPage = lazyPage(() => import('./owner/MyListingsPage'), 'MyListingsPage')
export const OwnerBookingsPage = lazyPage(() => import('./owner/OwnerBookingsPage'), 'OwnerBookingsPage')
export const OwnerCalendarPage = lazyPage(() => import('./owner/OwnerCalendarPage'), 'OwnerCalendarPage')
export const OwnerDisputeDetailPage = lazyPage(() => import('./owner/OwnerDisputeDetailPage'), 'OwnerDisputeDetailPage')
export const OwnerDisputesPage = lazyPage(() => import('./owner/OwnerDisputesPage'), 'OwnerDisputesPage')
export const OwnerEarningsPage = lazyPage(() => import('./owner/OwnerEarningsPage'), 'OwnerEarningsPage')
export const OwnerHomePage = lazyPage(() => import('./owner/OwnerHomePage'), 'OwnerHomePage')
export const OwnerLayout = lazyPage(() => import('./owner/OwnerLayout'), 'OwnerLayout')
export const OwnerReviewsPage = lazyPage(() => import('./owner/OwnerReviewsPage'), 'OwnerReviewsPage')
export const OwnerVerificationPage = lazyPage(() => import('./owner/OwnerVerificationPage'), 'OwnerVerificationPage')
